FROM antonioglass/salad-worker-a1111:pj-1.1

WORKDIR /

# Add Salad Job Queue Worker
ADD https://github.com/SaladTechnologies/salad-cloud-job-queue-worker/releases/download/v0.3.0/salad-http-job-queue-worker_x86_64.tar.gz /tmp
RUN tar -C /usr/local/bin -zxpf /tmp/salad-http-job-queue-worker_x86_64.tar.gz && \
    rm -rf /tmp/salad-http-job-queue-worker_x86_64.tar.gz

# Set permissions for scripts
COPY start.sh /start.sh
RUN chmod +x /start.sh

# Update app.py
COPY middleware/app.py /middleware/app.py

# Start the container
CMD /start.sh